global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'counter-metrics'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['counter-service:8080']