version: "3"
services:
  counter-service:
    build: ./../../../.
    image: counter-service:0.0.1
    container_name: counter-service
    ports:
      - "8080:8080"
    environment:
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yaml"
    external_links:
      - counter-service:counter-service
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    external_links:
      - prometheus:prometheus

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local